services:

  mock_api:
    build:
      context: ./mock_api
    ports:
      - "5000:5000"

  runner:
    build:
      context: .
    depends_on:
      - mock_api
    environment:
      MOCK_API_URL: http://mock_api:5000
      TARGET_FPS: "5"
      DEBUG_MODE: "false"